{
    'name': 'Reset Stages',
    'version': '17.0.1.0.0',
    'category': 'Productivity',
    'summary': 'Reset the stages for deleting the records',
    'author': 'Palo Dev',
    'license': 'LGPL-3',
    'depends': ['base', 'stock', 'mrp', 'purchase'],
    'data': [
        'views/stock_picking_views.xml',
        'views/mrp_production_views.xml',
        'views/mrp_unbuild_views.xml',
        'views/purchase_order_views.xml',
        'views/stock_quant_views.xml',
        'views/stock_scrap_views.xml',
    ],
    'installable': True,
    'application': False,
    'auto_install': False,
}
