{
    'name': 'Project Name',
    'version': '17.0.1.0.0',
    'category': 'Project',
    'summary': 'Project Name',
    'author': 'Palo Dev',
    'license': 'LGPL-3',
    'depends': [
        'base',
        'web',
        'project',
        'documents',
        'analytic',
        'sale_project'
    ],
    'data': [
        'security/ir.model.access.csv',
        'data/project_department_data.xml',
        'data/project_department_stage_data.xml',
        'data/project_department_task_data.xml',
        'data/project_group_data.xml',
        'views/project_department_views.xml',
        'views/project_group_views.xml',
        'views/project_project_simplified_views.xml',
        'views/project_project_edit_views.xml',
        'views/project_quick_create_views.xml',
        'views/project_menu.xml',
        'views/project_kanban.xml',
        'views/project_delete_wizard_views.xml',
        'views/mail_invite_views.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'project_name/static/src/scss/project_status_colors.scss',
        ],
    },
    'installable': True,
    'application': False,
    'auto_install': False,
}