{
    "name": "Employee Settings",
    "version": "17.0.1.0.0",
    "author": "Light up Total Solution Public Company Limited",
    "website": "https://www.lightuptotal.co.th/",
    "category": "Employees",
    "license": "LGPL-3",
    "icon": "web/static/lts/icon.png",
    "depends": [
        "base",
        "hr",
        "contacts",
        "contact_settings",
        "web",
    ],
    "data": [
        "security/ir.model.access.csv",
        "views/hr_employee_views.xml",
        "views/hr_employee_list_views.xml",
        "views/hr_employee_kanban_views.xml",
    ],
    "assets": {},
    "installable": True,
    "application": False,
    "auto_install": False,
}
